### Site Settings ###
title               : ADZGuy
description         : >-                               # >- means to ignore newlines until "url:"
                      I turn coffee into code,
                      use tabs over spaces
                      and never broke production.

url                 : "https://adzguy.github.io"                               # base hostname & protocol for your site (e.g. http://example.com)
baseurl             : "/portfolio"                    # subpath of your site (e.g. /blog) [IMPORTANT: use "" if your are hosting at https://username.github.io directly]
repository          : adzguy/portfolio    # repository metadata on GitHub Pages [know more at https://help.github.com/en/articles/repository-metadata-on-github-pages]
# remote_theme       : YoussefRaafatNasry/portfolYOU    # uncomment this if you are using it as a remote theme

### Author Info ###
author:
  name              : Davron Nurmetov
  image             : https://lh3.googleusercontent.com/ayugvi1QCLaxbXTjHo54-bb-BN4AQdNbPfls8aQRI6yg5TRkcSwO8NNX1oxh3tLCxFS9e9yL_yRoi-PtmD4q7jhFzyJDXvG8tkPpNeJwLZ1HNRsiNVyBiZYEPjGSwMH4BZNwW3WHyXtlolvX_hqA_E3svQ0b5p2Yj07kyXs2HyViAZ931g5sVR-FYOQENON6zUvmX6rziT5vCLfK3oaMKLZYlbpjG15mwZ7WhidpSYbtx_rCE6HYl4ZsF1xlGM6mt3lCE-QZiK8C516WTmHjy3y9ulwyUG2eKY-znJW5FKfwhfQUgM7A506pL1WsCsc0TCCKWsgcu_4nrI6xemZDfRnAtnajvqq6KQcYalGT5qDt8Zy2oNqQxQ87YqE0FX9WG7Wep4yY7kCzyvKE5X-KH2tqKaf4sCqdaBK9H_x2R1DI3LrbqeUyTtAqj9YMno0YUoCPTWPyEs51nwBkfjdg5SZXURLtTmEinDYYnCGpS84uJsoU0tFn_VocMs2-CCVLuTJaI5jjByIAvIDB9076QpGKXols8ACCF3STP0TZDuYZFB6RubbwBRTGqNOT7Z_JjrdhhBk3qssXQj-B07_GPiCUkkMoFvYB76R_bTvRgFVS6j-8iYo3FvMWVELmgJPwkNVxXgYlnkZkArONtakmzNAtx3WPLOX7e_AE2vSGx1Pmtw5nJqqvbw=s562-no
# behance           : your_username
# dribbble          : your_username
  email             : davron.nurmetov@gmail.com
# facebook          : your_username
  github            : adzguy
# gitlab            : your_username
# instagram         : your_username
  linkedin          : ndavron
# medium            : your_username
# soundcloud        : your_username
# spotify           : your_username
# stackoverflow     : your_user_id
# tumblr            : your_username.tumblr.com
# twitch            : your_username
  twitter           : imadzguy
# vimeo             : your_username
# youtube           : your_channel_name




### Pagination ###
paginate: 6
paginate_path: "/articles/page-:num/"


### Posts Permalink ###
permalink: articles/:title


### Collections ###
collections:
  projects:
    output: true
    permalink: /projects/:name


### Defaults for collections ###
defaults:
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "page"


### Exclude from processing ###
exclude:
- README.md
- CONTRIBUTING.md
- LICENSE
- Gemfile
- Gemfile.lock
